### PR TITLE
Add a ruletype that ensures that at least one workflow is triggered by pull_request

### PR DESCRIPTION
**Pull request by jhrozek**
This can be indicative of having a CI/CD pipeline

### CODE REVIEW

**Comment by jhrozek** [comment]
@ethomson 👀

**Comment by ethomson** [comment]
:excellent:

**Comment by eleftherias** [comment]
@jhrozek Is there a story this should be tied to? (genuine question, not implying you should create a story)

**Comment by jhrozek** [comment]
> @jhrozek Is there a story this should be tied to? (genuine question, not implying you should create a story)

There's a story of @ethomson pinging me on Slack asking me to do this :-P

No, really, this is related to PR #192 - having an extra ruletype would make the scorecard profile more complete. And since I was already working on PR #195 which is almost the same (just one is positive and one is negative and the event string is different), I was a straightforward thing to do.

**Review by eleftherias — APPROVED** [review]

**Comment by jhrozek** [comment]
btw we either need to fix the tests (PR #199 ) or I need to remove the test implementation for now from the PR

**Comment by jhrozek** [comment]
resubmitted without tests so we can merge faster - I'll submit the tests separately once we have the harness to run them merged.

**Comment by jhrozek** [comment]
(btw I made sure this rule works in Stacklok cloud prod and therefore that the JQ/rego dependencies have been deployed)

**Review by rdimitrov — APPROVED** [review]

**Pull request merged**
